workpc:
  short_name: workpc
  dmvio_folder: /home/cn1732/workspace/dm-vio
  pc_config_path:
  pc_config_command: apt list
  slurm: false
  results_path: /home/cn1732/workspace/SLAM_EVAL/dmvio
  euroc:
    dataset_path: datasets/euroc
    results_path: /home/cn1732/workspace/SLAM_EVAL/dmvio
  tumrs:
    dataset_path: /home/cn1732/workspace/SLAM_DATA/TUM_RS
    results_path: /home/cn1732/workspace/SLAM_EVAL/dmvio

config_general: # This is where configuration shared for all machines is stored (mainly dataset-specifics).
  euroc: # With start times as used by DSO and VI-DSO.
    afterpath: mav0/cam0/
    res_prefix: mav_
    dataset_args: files=./data calib=./camera.txt mode=1
    default_iter: 1
    folder_names: [MH_01_easy, MH_02_easy, MH_03_medium, MH_04_difficult, MH_05_difficult,
      V1_01_easy, V1_02_medium, V1_03_difficult, V2_01_easy, V2_02_medium, V2_03_difficult]
    # We use the start times proposed in the DSO paper, which were also taken over in VI-DSO.
    # When starting from the beginning, the method works also well, but then the setting
    # --dmvio_args="init_ba_skipFirstKFs=1 init_requestFullResetNormalizedErrorThreshold=0.8" should be used, which
    # improves the robustness of the method to bad visual initialization.
    start_times: [950, 800, 410, 445, 460, 22, 115, 250, 26, 100, 115]
    end_times: [3600, 3000, 2600, 1925, 2200, 2800, 1600, 2020, 2130, 2230, 1880]
  tumvi:
    afterpath: dso/cam0/
    afterpath2: dso/cam1/
    res_prefix: tumvi_
    dataset_args: files=./images calib=${DMVIO_PATH}/configs/tumvi_calib/camera02.txt
      gamma=${DMVIO_PATH}/configs/tumvi_calib/pcalib.txt vignette=vignette.png imuFile=../imu.txt
      gtFile=../gt_imu.csv imuCalib=${DMVIO_PATH}/configs/tumvi_calib/camchain.yaml
      mode=0 use16Bit=1
    default_iter: 1
    folder_names: [dataset-corridor1_512_16, dataset-corridor2_512_16, dataset-corridor3_512_16,
      dataset-corridor4_512_16, dataset-corridor5_512_16, dataset-magistrale1_512_16,
      dataset-magistrale2_512_16, dataset-magistrale3_512_16, dataset-magistrale4_512_16,
      dataset-magistrale5_512_16, dataset-magistrale6_512_16, dataset-outdoors1_512_16,
      dataset-outdoors2_512_16, dataset-outdoors3_512_16, dataset-outdoors4_512_16,
      dataset-outdoors5_512_16, dataset-outdoors6_512_16, dataset-outdoors7_512_16,
      dataset-outdoors8_512_16, dataset-room1_512_16, dataset-room2_512_16, dataset-room3_512_16,
      dataset-room4_512_16, dataset-room5_512_16, dataset-room6_512_16, dataset-slides1_512_16,
      dataset-slides2_512_16, dataset-slides3_512_16]
    # We always skip the first two frames in case the IMU data starts later than the images. This is just for convenience
    # (eliminates one possible source of error) and should not really make a difference.
    start_times: [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
      2, 2, 2, 2, 2, 2]
  tumrs:
    afterpath: dso/cam0/
    res_prefix: tumrs_
    dataset_args: files=./images calib=${DMVIO_PATH}/configs/tumrs_calib/camera0.txt
      imuFile=../imu.txt
      imuCalib=${DMVIO_PATH}/configs/tumrs_calib/camchain.yaml
      mode=1 use16Bit=1
    default_iter: 1
    folder_names: [dataset-seq1,dataset-seq2,dataset-seq3,dataset-seq4,dataset-seq5,dataset-seq6,dataset-seq7,dataset-seq8,dataset-seq9,dataset-seq10]
    # We always skip the first two frames in case the IMU data starts later than the images. This is just for convenience
    # (eliminates one possible source of error) and should not really make a difference.
    start_times: [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
      2, 2, 2, 2, 2, 2]